// // Assignment Code
var generateBtn = document.getElementById("generate");// a variable to select the generate button and store result


// Write password to the #password input


// Add event listener to create password button

var passLength = prompt ("how many characters in your password?");
var lowerCase = confirm("Would you like to include lowercase letters?") 
var upperCase = confirm("Would you like to include uppercase letters?")
var specialCase = confirm("Would you like to include special characters !#@%^>> ?")
var numberCase = confirm("Would you like to include numbers?") 

var passLengthInteger = parseInt(passLength) //based on user selection, length turned from string into integer

// // Random Character Generator - these should only run if "true"element selected up above

function generatePassword(){//what user selected, length of what you want
  var compiledPassword = "";
  
  var lowerCharSet = "abcdefghijklmnopqrstuvwxyz";
  var upperCharSet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  var numberCharSet = "0123456789";
  var specialCharSet = "@#$%^&*";
  var finalPassword = "";
  if (lowerCase){
    compiledPassword+=lowerCharSet 
  }
  
  if (upperCase){
    compiledPassword+=upperCharSet 
  }
  
  if (numberCase){
    compiledPassword+=numberCharSet 
  }
  
  if (specialCase){
    compiledPassword+=specialCharSet 
  }
  for (var i=0; i<passLengthInteger; i++) { //if user has selected 10 character, for loops will run 10 times, we want random
    finalPassword+= compiledPassword.charAt(Math.floor(Math.random()*compiledPassword.length))
  }
  return finalPassword
  
}



function writePassword() { //a function to writePassword, logic is as follows, finished password = generatePass
  
  var passwordText = document.querySelector("#password"); //targeted the password id in html to be stored as passText variable
  var password = generatePassword(); //final password is generated by some event, then a function
  passwordText.innerHTML = password;
  
}
generateBtn.addEventListener("click", writePassword);


